name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [11, 15, 17]

    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Check Docs
        run: ./util/check_docs.py
      - name: Set up JDK
        uses: actions/setup-java@v4
        distribution: jdk
        with:
          java-version: ${{ matrix.java }}
      - name: CI Test
        run: mvn verify
      - name: Upload Artifact
        if: ${{ matrix.java == 11 }}
        uses: actions/upload-artifact@v4
        with:
          name: robot.jar 
          path: bin/robot.jar
          retention-days: 90
